"""SQLAlchemy ORM model for recommendations.

Every recommendation stores its score_breakdown JSONB so users can see
why something was recommended and developers can analyze which scorers
drive engagement (Decision 007).
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Index
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.core.database import Base, TimestampMixin


class Recommendation(TimestampMixin, Base):
    """A personalized event recommendation for a user.

    Generated by the recommendation engine from multiple scoring
    strategies. The score_breakdown field provides transparency
    into why each event was recommended.

    Attributes:
        id: Unique identifier for the recommendation.
        user_id: Foreign key to the user this recommendation is for.
        event_id: Foreign key to the recommended event.
        score: Normalized final score from 0.0 to 1.0.
        score_breakdown: JSONB with per-scorer scores and reasoning
            (e.g., {"artist_match": 0.8, "similar_artist": 0.3}).
        generated_at: When this recommendation was generated.
        is_dismissed: Whether the user dismissed this recommendation.
        user: Relationship to the target user.
        event: Relationship to the recommended event.
    """

    __tablename__ = "recommendations"
    __table_args__ = (
        Index(
            "ix_recommendations_user_score",
            "user_id",
            "score",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    score: Mapped[float] = mapped_column(Float, nullable=False)
    score_breakdown: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=datetime.utcnow,
    )
    is_dismissed: Mapped[bool] = mapped_column(
        default=False, nullable=False
    )

    # Relationships
    user: Mapped["User"] = relationship(  # noqa: F821
        back_populates="recommendations",
    )
    event: Mapped["Event"] = relationship()  # noqa: F821

    def __repr__(self) -> str:
        """Return a string representation of the Recommendation.

        Returns:
            String representation with user, event, and score.
        """
        return (
            f"<Recommendation user={self.user_id} "
            f"event={self.event_id} score={self.score:.2f}>"
        )
