"""add_region_to_cities

Revision ID: bde6f81e7ff5
Revises: b42792273897
Create Date: 2026-04-17 09:36:21.539869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde6f81e7ff5'
down_revision: Union[str, None] = 'b42792273897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('region', sa.String(length=20), nullable=False, server_default='DMV'))
    op.create_index(op.f('ix_cities_region'), 'cities', ['region'], unique=False)
    # Remove server default after backfill — app handles defaults
    op.alter_column('cities', 'region', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_region'), table_name='cities')
    op.drop_column('cities', 'region')
    # ### end Alembic commands ###
